site_name: Mbodi Handbook
repo_url: https://github.com/mbodi/handbook
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.png
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - Company:
      - Mission & Vision: company/mission.md
      - Values: company/values.md
      - Product Principles: company/product-principles.md
      - How We Hire: company/how-we-hire.md
      - OKRs: company/okrs.md
      - Organization: company/organization.md
      - Communication: company/communication.md
      - Tools We Use: company/tools.md
  - Research:
      - Index: research/index.md
  - Engineering:
      - Index: engineering/index.md
      - ADRs: engineering/adr/index.md
      - RFCs: engineering/rfcs/index.md
      - Runbooks: engineering/runbooks/index.md
  - Business:
      - Index: business/index.md
  - Operations: ops/index.md
  - People: people/index.md
  - Finance: finance/index.md
  - Security: security/index.md
  - Legal: legal/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter:
      execute: false

extra_css:
  - assets/brand.css
